spring:
  application:
          name: zuul-api-gateway

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
  instance:
    nonSecurePort: 80
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:   info, health, refresh
        
zuul:
  host:
    socket-timeout-millis: 120000
    connect-timeout-millis: 120000
    connection-request-timeout-millis: 120000

ribbon:
  ConnectTimeout: 120000
  ReadTimeout: 120000
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 240000 
        timeout:
          enabled: false
          
sample-efs-inservice: true
sample-employee-microservice-healthcheck-url: http://localhost:8090/actuator/health